
# **01-Introduction-to-Deep-Learning-with-PyTorch**


In [ ]:
# !git clone <path>

In [ ]:
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# import seaborn as sns
# import os

# # plt.style.use('ggplot')
# # sns.set_theme(style='whitegrid')
# %matplotlib inline


In [ ]:
# os.chdir('path to the dataset')
# cwd = os.getcwd()
# print('Curent working directory is ', cwd)

In [ ]:
# ls

## **1️⃣Introduction to PyTorch, a Deep Learning Library**

**Tensors: the building blocks of networks in PyTorch**

In [ ]:
# Load from list
import torch

lst = [[1, 2, 3], [4, 5, 6]]
tensor = torch.tensor(lst)

print(tensor)
print(type(tensor))

tensor([[1, 2, 3],
        [4, 5, 6]])
<class 'torch.Tensor'>


In [ ]:
# Load from NumPy array
import numpy as np

array = [[1, 2, 3], [4, 5, 6]]
np_array = np.array(array)
print(np_array)

print("\n")

np_tensor = torch.tensor(np_array)
print(np_tensor)

[[1 2 3]
 [4 5 6]]


tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
# Tensor attributes
import torch

lst = [[1, 2, 3], [4, 5, 6]]
tensor = torch.tensor(lst)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([2, 3])
torch.int64
cpu


> PyTorch doesn't guarantee the exact data type by default. It might allocate a different data type based on the hardware and software configuration. To ensure `32-bit` floats, you can explicitly specify it during creation:

In [ ]:
import torch

lst_32 = [[1, 2, 3], [4, 5, 6]]
tensor = torch.tensor(lst_32, dtype=torch.float32)

print(tensor.dtype)

torch.float32


**Tensor Operations**

In [ ]:
a = torch.tensor([[1, 1],
                 [2, 2]])

b = torch.tensor([[2, 2],
                  [3, 3]])

c = torch.tensor([[1, 1, 4],
                  [2, 2, 5]])

In [ ]:
print(a+b)

tensor([[3, 3],
        [5, 5]])


In [ ]:
print(a-b)

tensor([[-1, -1],
        [-1, -1]])


In [ ]:
try:
  print(a + c)
except RuntimeError as e:
  print("Error:", e)

Error: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1


In [ ]:
print(a*b)

tensor([[2, 2],
        [6, 6]])


**Neural Network (NN) Vs. Convolutional Neural Network (CNN)**
             


| Feature             | Neural Network (NN)                                            | Convolutional Neural Network (CNN)                                     |
|---------------------|-----------------------------------------------------------------|-------------------------------------------------------------------------|
| Type                | General purpose                                                 | Subtype of NN, specialized for grid-like data (images)                  |
| Architecture        | Fully-connected layers                                          | Convolutional layers, pooling layers, and fully-connected layers        |
| Data Processing     | Each neuron in a layer connected to all neurons in the previous layer | Local connections between neurons, exploiting spatial relationships in data |
| Parameter Efficiency | Less efficient, requires more parameters                       | More efficient, learns features automatically                           |
| Strengths           | Flexible, works well for various data types                     | Excellent for image recognition, computer vision                         |
| Applications        | Classification, regression, pattern recognition                 | Image classification, object detection, image segmentation              |


**Creating the Neural Network**

In [ ]:
# Single Layer NN
import torch.nn as nn

# Create input_tensor with three features
input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])

# Define our first linear layer
# linear_layer = nn.Linear(3, 2)
linear_layer = nn.Linear(in_features=3, out_features=2)

# Pass input through linear layer
output = linear_layer(input_tensor)

print(output)
print(linear_layer.weight) # Each layer has a weight
print(linear_layer.bias)   # and bias property

tensor([[0.1131, 0.2126]], grad_fn=<AddmmBackward0>)
Parameter containing:
tensor([[-0.2639, -0.2151,  0.3009],
        [ 0.4829,  0.1614,  0.5067]], requires_grad=True)
Parameter containing:
tensor([0.3734, 0.0909], requires_grad=True)


`output = linear_layer(input_tensor)`

for input $X$, weights $W_0$ and bias $b_0$, the linear layer performs

$y_0 = W_0.X + b_0$

- **In PyTorch**:
    - Weights and bias are initialized randomly
    - They are not useful until they are tuned


**Our two-layer network summary**

- Input dimensions: `1 × 3`
- Linear layer arguments:
    - in_features = `3`
    - out_features = `2`
- Output dimensions: `1 × 2`
- Networks with only linear layers are called **fully connected**.
- Each neuron in one layer is connected to
each neuron in the next layer

In [ ]:
# Stacking layer with nn.Sequential() - Multiple Layer NN

import torch.nn as nn

# Create input_tensor with three features
input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]]) # Dim:1x3

# Define the model with the first layer matching input features
model = nn.Sequential(
    nn.Linear(3, 5),
    nn.Linear(5, 7),
    nn.Linear(7, 5)
)

# Pass input through the model
output_tensor = model(input_tensor)
print(output_tensor)

tensor([[-0.3508,  0.1057, -0.0417, -0.0351, -0.6433]],
       grad_fn=<AddmmBackward0>)


In [ ]:
# Stacking layer with Activation function
import torch
from torch import nn

# Create input_tensor with three features
input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]]) # Dim:1x3

# Define the model using nn.Sequential
model = nn.Sequential(
    nn.Linear(3, 5),    # First linear layer with 3 input features and 5 hidden units
    nn.ReLU(),          # Activation function (ReLU in this case)
    nn.Linear(5, 7),    # Second linear layer with 5 input features (from previous layer) and 7 hidden units
    nn.ReLU(),          # Activation function (ReLU again)
    nn.Linear(7, 2)     # Output layer with 7 input features (from previous layer) and 2 output units
)

# Print the model architecture
print(model)

# Pass input through the model
output_tensor = model(input_tensor)
print(output_tensor)

Sequential(
  (0): Linear(in_features=3, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=7, bias=True)
  (3): ReLU()
  (4): Linear(in_features=7, out_features=2, bias=True)
)
tensor([[ 0.4343, -0.1482]], grad_fn=<AddmmBackward0>)


**Discovering Activation functions**

- Non-linearity allows neural networks to learn and represent complex patterns and relationships in data.

- Activation functions introduce non-linearity by transforming the input signal into an output signal.

- Without activation functions, neural networks would only be able to model linear relationships, limiting their capacity to learn and generalize.

- Activation functions introduce important properties like boundedness and differentiability, which aid in optimization during training.

- They enable neural networks to approximate any arbitrary function, making them  powerful tools for various tasks such as classification, regression, and reinforcement learning.

- Common activation functions include `sigmoid`, `tanh`, `ReLU` (Rectified Linear Unit), and variants like Leaky `ReLU` and `ELU` (Exponential Linear Unit).

These functions introduce complexity and flexibility, enabling neural networks to capture intricate data patterns and improve model performance.

```python
# Sigmoid

input_tensor = torch.tensor([[0.8]])

# Create a sigmoid function and apply it on input_tensor
sigmoid = nn.Sigmoid()
probability = sigmoid(input_tensor)
print(probability)
```


```python
# Softmax

input_tensor = torch.tensor([[1.0, -6.0, 2.5, -0.3, 1.2, 0.8]])

# Create a softmax function and apply it on input_tensor
softmax = nn.Softmax(dim=-1)
probabilities = softmax(input_tensor)
print(probabilities)
```

**Sigmoid**

In [ ]:
# Neural Network

import torch
import torch.nn as nn

# Define the NN model
model = nn.Sequential(
    nn.Linear(6, 4),  # First linear layer
    nn.Linear(4, 1),  # Second linear layer
    nn.Sigmoid()      # Sigmoid activation function
)

# Example usage
input_tensor = torch.tensor([[6.0, 0.0, 0.0, 0.0, 0.0, 0.0]])
output = model(input_tensor)
print(output)

tensor([[0.5914]], grad_fn=<SigmoidBackward0>)


In [ ]:
# Convolutional Neural Network

import torch
import torch.nn as nn

# Define the CNN model
model = nn.Sequential(
    nn.Conv2d(in_channels=3, out_channels=16, kernel_size=3, stride=1, padding=1),
    nn.ReLU(),
    nn.MaxPool2d(kernel_size=2, stride=2),
    nn.Conv2d(in_channels=16, out_channels=32, kernel_size=3, stride=1, padding=1),
    nn.ReLU(),
    nn.MaxPool2d(kernel_size=2, stride=2),
    nn.Flatten(),
    nn.Linear(32 * 56 * 56, 128),  # 32 channels, 56x56 image size after pooling
    nn.ReLU(),
    nn.Linear(128, 1),             # Output layer for binary classification
    nn.Sigmoid()                   # Sigmoid activation function
)

# Example usage
input_tensor = torch.randn(1, 3, 224, 224)  # Example input tensor with shape (batch_size, channels, height, width)
output = model(input_tensor)
print(output)

tensor([[0.5102]], grad_fn=<SigmoidBackward0>)


- A neural network with a `single linear layer` followed by a `sigmoid` activation is similar to a **logistic regression model**.

- The `input` dimension of a linear layer must be **equal** to the `output` dimension of the previous layer.

**Softmax**

In [ ]:
import torch
import torch.nn as nn

# Define the NN model
model = nn.Sequential(
    nn.Linear(3, 4),   # First linear layer
    nn.Linear(4, 3),   # Second linear layer, output size 3 for softmax
    nn.Softmax(dim=-1) # -1 indicates softmax is applied to the input tensor's last dimension
)                      # nn.Sigmoid() can be used as last step in nn.Sequential()

# Example usage
input_tensor = torch.tensor([[4.3, 6.1, 2.3]])
output = model(input_tensor)
print(output)

tensor([[0.2073, 0.1959, 0.5968]], grad_fn=<SoftmaxBackward0>)


## **2️⃣Training Our First Neural Network with PyTorch**

## **3️⃣Neural Network Architecture and Hyperparameters**

## **4️⃣Evaluating and Improving Models**

#### $\color{skyblue}{\textbf{Connect with me:}}$


[<img align="left" src="https://cdn4.iconfinder.com/data/icons/social-media-icons-the-circle-set/48/twitter_circle-512.png" width="32px"/>][twitter]
[<img align="left" src="https://cdn-icons-png.flaticon.com/512/145/145807.png" width="32px"/>][linkedin]
[<img align="left" src="https://cdn2.iconfinder.com/data/icons/whcompare-blue-green-web-hosting-1/425/cdn-512.png" width="32px"/>][Portfolio]

[twitter]: https://twitter.com/F4izy
[linkedin]: https://www.linkedin.com/in/mohd-faizy/
[Portfolio]: https://mohdfaizy.com/
